### PR TITLE
First working implementation

### PR DESCRIPTION
**Pull request by lucav76**

### CODE REVIEW

**Comment by kkweon** [comment]
Confirmed it's running very well. Great work!
I have one question though.

## Dependencies
it currently depends on `sklearn`, `skimage` and `cv2`, but according to the requirement, 
> **The project that is evaluated on the vehicle should not have any external libraries that aren't included in the starter repo.** - [Link](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/project)

The starter repo includes the following libraries.
```text
Flask==0.11.1
attrdict==2.0.0
eventlet==0.19.0
python-socketio==1.6.1
numpy==1.13.1
Pillow==2.2.1
scipy==0.19.1
keras==2.0.8
tensorflow==1.3.0
h5py==2.6.0
```
So, `sklearn`, `skimage` and `cv2`  are not included.
(Though I am pretty sure `cv2` will work because I know other people who have used it)
What do you guys think?

**Comment by TimSoft77** [comment]
https://discussions.udacity.com/t/svm-as-traffic-light-classifier/389093

Sadly, I think this rules out sklearn.  I can't find anything on cv2.

I'll try to check if it works on the VM provided by Udacity today.

One question to help finish the waypoint_updater: when the traffic light goes green (i.e., there used to be a read traffic light ahead, and now there is not), what gets published to /traffic_waypoint?

**Comment by jocmom** [comment]
Just had a short look on the code but I think Luca used sklearn and skimage mainly for augmentation and training, this should be OK right?
Not sure about cv2 either.

**Comment by lucav76** [comment]
I might try to reduce the dependencies, during inference.

**Comment by Krishtof-Korda** [comment]
@lucav76  , please confirm and merge this if you have no other major additions right now. Small tweaks can be added after merge in master.

**Pull request merged**
